# Generated by Django 4.2.16 on 2026-01-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_faq_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='name',
            field=models.CharField(default='firstname', max_length=100),
        ),
    ]
