# Generated by Django 4.2.16 on 2026-01-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_newslettersubscriber_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='active',
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
