# Generated by Django 4.2.16 on 2026-01-29 16:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
